graph LR
    CF[ContractFlow]
    ESB{MuleSoft ESB}
    CF --> ESB
    ESB -->|REST| SAP[SAP ECC]
    ESB -->|REST| SF[Salesforce]
    ESB -->|SOAP| TOTVS[TOTVS Protheus]
    ESB -->|Kafka| TMS[Manhattan TMS]
    ESB -->|Kafka| WMS[WMS Infor]
    ESB -->|REST| DS[DocuSign]
    ESB -->|SOAP| SEF[SEFAZ]
    ESB -->|SOAP| SPED[SPED]
    ESB -->|SOAP| ESO[e-Social]
    ESB -->|REST| SER[Serasa]
    ESB -->|REST| SPC[SPC]
    ESB -->|REST HMAC| BAN[Gateway Banco]
    ESB -->|REST| BOL[Boletos]
    ESB -->|CDC| DL[Data Lake]
    ESB -->|Dataset API| BI[Power BI]
    ESB -->|REST| POR[Portal PHP]
    ESB -->|Adapter| COB[Cobol Cobranca]
    ESB -->|ODBC| VB6[VB6 Comissoes]
    ESB -->|SFTP| ACC[Access Regional]
    ESB -->|Graph| GED[GED SharePoint]
    ESB -->|Watcher| PLA[Planilhas Criticas]
    ESB -->|SMTP| EMA[E-mail Corp]
